
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
      